name:  hygi_health
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

# Versioning
version: 1.0.0+1

# Flutter and Dart SDK environment
environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.0
  dio: ^5.7.0  # Required for Retrofit
  json_annotation: ^4.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^1.0.0
#  geolocator: ^9.0.2 # Force version 10.0.0
#  firebase_messaging: ^14.6.5
#  firebase_core: ^2.14.0 # Or the latest version
  intl: ^0.18.1

#  image_picker: ^0.8.7+5
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.9
  permission_handler: ^10.2.0
# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0 # Specify the correct version or latest

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # Android min SDK: 16, default: 21

# Flutter-specific configurations
flutter:
  uses-material-design: true
  fonts:
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope-Regular.ttf
      - asset: assets/fonts/Manrope-Bold.ttf
        weight: 700
      - asset: assets/fonts/Manrope-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Manrope-SemiBold.ttf
        style: italic

  assets:
    - assets/splash.png
    - assets/banner.png
    - assets/mobile.png
    - assets/logo.png
    - assets/slider.png
    - assets/mycart.png
    - assets/wallet.png
    - assets/backarrow.png
    - assets/right.png
    - assets/mycart.png
    - assets/profile.png
    - assets/calendar.png
    - assets/mango.png
    - assets/person.png
    - assets/cart.png
    - assets/info.png
    - assets/location.png
    - assets/privacy.png
    - assets/no_products.png

